In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

EX.6 How to sorted Dictionary by value
#sorted(...)

['Business Data Mining',
 'Business Data Visualization',
 'Enterprise Database',
 'Independent Study']

In [9]:
#EX.6 How to sorted Dictionary by value #sorted(...)
course = {
  "954340": "Enterprise Database",
  "954471": "Business Data Mining",
  "954472": "Business Data Visualization"
}
print(sorted(course.values()))

['Business Data Mining', 'Business Data Visualization', 'Enterprise Database']

In [17]:
#Example Comprehensive
L = ["A", "B", "C"]
a = [item for item in L]
a

['A', 'B', 'C']

In [19]:
#Example Comprehensive
a = [item*2 for item in L if item is not 'B']
a

['AA', 'CC']

In [22]:
#Example Comprehensive
a = [item+item2 for item in L for item2 in L]
a

['AA', 'AB', 'AC', 'BA', 'BB', 'BC', 'CA', 'CB', 'CC']

In [20]:
#Example Comprehensive
L = ["A", "B", "C"]
a = [item for item in L if item not in ['A','B']]
a

['C']

In [25]:
#Example Function
def summation(L):
    z = ""
    for item in L:
        z = z + item
    return z

c = summation(['a','b','c'])
c

'abc'

In [36]:
#Example Function
def multi(start, end):
    for i in range(start, end+1):
        for j in range(12):
            print(str(i)+"x"+str(j+1),"=",str(i*(j+1)))
        print("\n")
    
multi(3,5)

3x1 = 3
3x2 = 6
3x3 = 9
3x4 = 12
3x5 = 15
3x6 = 18
3x7 = 21
3x8 = 24
3x9 = 27
3x10 = 30
3x11 = 33
3x12 = 36


4x1 = 4
4x2 = 8
4x3 = 12
4x4 = 16
4x5 = 20
4x6 = 24
4x7 = 28
4x8 = 32
4x9 = 36
4x10 = 40
4x11 = 44
4x12 = 48


5x1 = 5
5x2 = 10
5x3 = 15
5x4 = 20
5x5 = 25
5x6 = 30
5x7 = 35
5x8 = 40
5x9 = 45
5x10 = 50
5x11 = 55
5x12 = 60

In [61]:
n = int(input())
for j in range(1, n+1):
    print("* " * j)

 5

*
* *
* * *
* * * *
* * * * *

In [59]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
odd, even = [el for el in numbers if el % 2==1], [el for el in numbers if el % 2==0]
print("Number of odd numbers:"+str(len(odd))+"\n" + "Number of even numbers:"+str(len(even)))

Number of odd numbers:5
Number of even numbers:4